# Generated by Django 6.0.2 on 2026-03-13 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image_url', models.URLField(blank=True)),
                ('supports_customization', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('diet_tags', models.CharField(blank=True, max_length=200)),
                ('mood_tags', models.CharField(blank=True, choices=[('comfort', 'Comfort'), ('healthy', 'Healthy'), ('cheat', 'Cheat Meal'), ('spicy', 'Spicy'), ('late-night', 'Late Night')], max_length=50)),
                ('ingredients', models.TextField(blank=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
            ],
        ),
    ]
